// Whole-program Ghidra probe for stores overlapping sideband byte ranges.

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSetView;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ProbeHp1020SidebandOverlapStoreScan extends GhidraScript {
    private static final Range[] TARGET_RANGES = {
        new Range("+0x26", 0x26, 0x27),
        new Range("+0x30", 0x30, 0x31),
        new Range("+0x32", 0x32, 0x33)
    };
    private static final long[] KNOWN_FUNCTION_STARTS = {
        0x10009b4cL,
        0x1000e414L,
        0x1000f204L,
        0x1000f228L,
        0x10010398L,
        0x100104c8L,
        0x10014910L
    };

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            println("usage: ProbeHp1020SidebandOverlapStoreScan <output-dir>");
            return;
        }

        File outDir = new File(args[0]);
        outDir.mkdirs();
        File outFile = new File(outDir, "sideband-overlap-store-scan.md");

        createKnownFunctions();
        List<Hit> hits = scanInstructions();

        try (PrintWriter out = new PrintWriter(new FileWriter(outFile))) {
            out.println("# HP 1020 Sideband Overlap Store Scan");
            out.println();
            out.println("This report is generated by headless Ghidra. It scans disassembled store instructions only and does not contact the printer.");
            out.println();
            out.println("## Import Context");
            out.println();
            out.println("- program: `" + currentProgram.getName() + "`");
            out.println("- language: `" + currentProgram.getLanguageID() + "`");
            out.println("- compiler spec: `" + currentProgram.getCompilerSpec().getCompilerSpecID() + "`");
            out.println("- target byte ranges: `+0x26..+0x27`, `+0x30..+0x31`, `+0x32..+0x33`");
            out.println("- matching overlapping stores: `" + hits.size() + "`");
            out.println();

            out.println("## Store Hits");
            out.println();
            out.println("| Address | Function | Mnemonic | Offset | Width | Overlaps | Bytes | Instruction |");
            out.println("|---|---|---|---:|---:|---|---|---|");
            for (Hit hit : hits) {
                out.printf("| `%s` | `%s` | `%s` | `0x%x` | `%d` | `%s` | `%s` | `%s` |%n",
                    hit.address,
                    hit.functionName,
                    hit.mnemonic,
                    hit.offset,
                    hit.width,
                    hit.overlaps,
                    hit.bytes,
                    hit.instruction.replace("|", "\\|"));
            }

            out.println();
            out.println("## Decompiled Hit Functions");
            out.println();
            Map<Function, Boolean> seen = new LinkedHashMap<>();
            for (Hit hit : hits) {
                if (hit.function != null) {
                    seen.put(hit.function, Boolean.TRUE);
                }
            }
            for (Function function : seen.keySet()) {
                out.println("### `" + function.getEntryPoint() + " " + function.getName() + "`");
                out.println();
                out.println("```c");
                out.print(decompile(function));
                out.println("```");
                out.println();
            }
        }
        println("wrote " + outFile.getAbsolutePath());
    }

    private void createKnownFunctions() throws Exception {
        for (long raw : KNOWN_FUNCTION_STARTS) {
            Address address = toAddr(raw);
            disassemble(address);
            Function function = getFunctionAt(address);
            if (function == null) {
                function = createFunction(address, "hp1020_probe_fn_" + Long.toHexString(raw));
            }
            if (function != null && function.getName().startsWith("hp1020_probe_fn_")) {
                function.setName("hp1020_probe_fn_" + Long.toHexString(raw), SourceType.ANALYSIS);
            }
        }
    }

    private List<Hit> scanInstructions() throws Exception {
        List<Hit> hits = new ArrayList<>();
        AddressSetView executable = currentProgram.getMemory().getExecuteSet();
        InstructionIterator instructions = currentProgram.getListing().getInstructions(executable, true);
        while (instructions.hasNext()) {
            Instruction instruction = instructions.next();
            Store store = parseStore(instruction.toString());
            if (store == null) {
                continue;
            }
            String overlaps = overlappingTargets(store.offset, store.width);
            if (overlaps.isEmpty()) {
                continue;
            }
            Function function = getFunctionContaining(instruction.getAddress());
            hits.add(new Hit(
                instruction.getAddress().toString(),
                function == null ? "<none>" : function.getEntryPoint() + " " + function.getName(),
                function,
                store.mnemonic,
                store.offset,
                store.width,
                overlaps,
                formatBytes(instruction.getBytes()),
                instruction.toString()
            ));
        }
        return hits;
    }

    private Store parseStore(String text) {
        String lower = text.toLowerCase();
        int width;
        String mnemonic;
        if (lower.startsWith("s8i ")) {
            mnemonic = "s8i";
            width = 1;
        }
        else if (lower.startsWith("s16i ")) {
            mnemonic = "s16i";
            width = 2;
        }
        else if (lower.startsWith("s32i.n ")) {
            mnemonic = "s32i.n";
            width = 4;
        }
        else if (lower.startsWith("s32i ")) {
            mnemonic = "s32i";
            width = 4;
        }
        else {
            return null;
        }
        int comma = lower.lastIndexOf(',');
        if (comma < 0 || comma + 1 >= lower.length()) {
            return null;
        }
        String offsetText = lower.substring(comma + 1).trim();
        if (!offsetText.startsWith("0x")) {
            return null;
        }
        try {
            int offset = Integer.parseUnsignedInt(offsetText.substring(2), 16);
            return new Store(mnemonic, offset, width);
        }
        catch (NumberFormatException ignored) {
            return null;
        }
    }

    private String overlappingTargets(int offset, int width) {
        int end = offset + width - 1;
        StringBuilder builder = new StringBuilder();
        for (Range range : TARGET_RANGES) {
            if (offset <= range.end && end >= range.start) {
                if (builder.length() > 0) {
                    builder.append(", ");
                }
                builder.append(range.name);
            }
        }
        return builder.toString();
    }

    private String decompile(Function function) {
        DecompInterface decompiler = new DecompInterface();
        try {
            decompiler.openProgram(currentProgram);
            DecompileResults result = decompiler.decompileFunction(function, 30, monitor);
            if (result == null || !result.decompileCompleted() || result.getDecompiledFunction() == null) {
                String error = result == null ? "null result" : result.getErrorMessage();
                return "/* decompile failed: " + error + " */\n";
            }
            return result.getDecompiledFunction().getC();
        }
        finally {
            decompiler.dispose();
        }
    }

    private String formatBytes(byte[] bytes) {
        StringBuilder builder = new StringBuilder();
        for (byte value : bytes) {
            if (builder.length() > 0) {
                builder.append(' ');
            }
            builder.append(String.format("%02x", value & 0xff));
        }
        return builder.toString();
    }

    private static class Range {
        final String name;
        final int start;
        final int end;

        Range(String name, int start, int end) {
            this.name = name;
            this.start = start;
            this.end = end;
        }
    }

    private static class Store {
        final String mnemonic;
        final int offset;
        final int width;

        Store(String mnemonic, int offset, int width) {
            this.mnemonic = mnemonic;
            this.offset = offset;
            this.width = width;
        }
    }

    private static class Hit {
        final String address;
        final String functionName;
        final Function function;
        final String mnemonic;
        final int offset;
        final int width;
        final String overlaps;
        final String bytes;
        final String instruction;

        Hit(String address, String functionName, Function function, String mnemonic, int offset, int width,
            String overlaps, String bytes, String instruction) {
            this.address = address;
            this.functionName = functionName;
            this.function = function;
            this.mnemonic = mnemonic;
            this.offset = offset;
            this.width = width;
            this.overlaps = overlaps;
            this.bytes = bytes;
            this.instruction = instruction;
        }
    }
}
