// Whole-program Ghidra probe for stores to sideband-looking halfword offsets.

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSetView;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ProbeHp1020SidebandStoreScan extends GhidraScript {
    private static final String[] TARGET_OFFSETS = {"0x26", "0x30", "0x32"};
    private static final long[] KNOWN_FUNCTION_STARTS = {
        0x10009b4cL,
        0x1000e414L,
        0x1000f204L,
        0x1000f228L,
        0x10010398L,
        0x100104c8L,
        0x10014910L
    };

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            println("usage: ProbeHp1020SidebandStoreScan <output-dir>");
            return;
        }

        File outDir = new File(args[0]);
        outDir.mkdirs();
        File outFile = new File(outDir, "sideband-store-scan.md");

        createKnownFunctions();
        List<Hit> hits = scanInstructions();

        try (PrintWriter out = new PrintWriter(new FileWriter(outFile))) {
            out.println("# HP 1020 Sideband Store Scan");
            out.println();
            out.println("This report is generated by headless Ghidra. It scans disassembled instructions only and does not contact the printer.");
            out.println();
            out.println("## Import Context");
            out.println();
            out.println("- program: `" + currentProgram.getName() + "`");
            out.println("- language: `" + currentProgram.getLanguageID() + "`");
            out.println("- compiler spec: `" + currentProgram.getCompilerSpec().getCompilerSpecID() + "`");
            out.println("- target offsets: `0x26, 0x30, 0x32`");
            out.println("- matching stores: `" + hits.size() + "`");
            out.println();

            out.println("## Store Hits");
            out.println();
            out.println("| Address | Function | Offset | Bytes | Instruction |");
            out.println("|---|---|---|---|---|");
            for (Hit hit : hits) {
                out.printf("| `%s` | `%s` | `%s` | `%s` | `%s` |%n",
                    hit.address,
                    hit.functionName,
                    hit.offset,
                    hit.bytes,
                    hit.instruction.replace("|", "\\|"));
            }

            out.println();
            out.println("## Decompiled Hit Functions");
            out.println();
            Map<Function, Boolean> seen = new LinkedHashMap<>();
            for (Hit hit : hits) {
                if (hit.function != null) {
                    seen.put(hit.function, Boolean.TRUE);
                }
            }
            for (Function function : seen.keySet()) {
                out.println("### `" + function.getEntryPoint() + " " + function.getName() + "`");
                out.println();
                out.println("```c");
                out.print(decompile(function));
                out.println("```");
                out.println();
            }
        }
        println("wrote " + outFile.getAbsolutePath());
    }

    private void createKnownFunctions() throws Exception {
        for (long raw : KNOWN_FUNCTION_STARTS) {
            Address address = toAddr(raw);
            disassemble(address);
            Function function = getFunctionAt(address);
            if (function == null) {
                function = createFunction(address, "hp1020_probe_fn_" + Long.toHexString(raw));
            }
            if (function != null && function.getName().startsWith("hp1020_probe_fn_")) {
                function.setName("hp1020_probe_fn_" + Long.toHexString(raw), SourceType.ANALYSIS);
            }
        }
    }

    private List<Hit> scanInstructions() throws Exception {
        List<Hit> hits = new ArrayList<>();
        AddressSetView executable = currentProgram.getMemory().getExecuteSet();
        InstructionIterator instructions = currentProgram.getListing().getInstructions(executable, true);
        while (instructions.hasNext()) {
            Instruction instruction = instructions.next();
            String text = instruction.toString();
            if (!isTargetStore(text)) {
                continue;
            }
            String offset = matchedOffset(text);
            Function function = getFunctionContaining(instruction.getAddress());
            hits.add(new Hit(
                instruction.getAddress().toString(),
                function == null ? "<none>" : function.getEntryPoint() + " " + function.getName(),
                function,
                offset,
                formatBytes(instruction.getBytes()),
                text
            ));
        }
        return hits;
    }

    private boolean isTargetStore(String text) {
        String lower = text.toLowerCase();
        if (!lower.startsWith("s16i")) {
            return false;
        }
        for (String offset : TARGET_OFFSETS) {
            if (lower.endsWith("," + offset)) {
                return true;
            }
        }
        return false;
    }

    private String matchedOffset(String text) {
        String lower = text.toLowerCase();
        for (String offset : TARGET_OFFSETS) {
            if (lower.endsWith("," + offset)) {
                return offset;
            }
        }
        return "unknown";
    }

    private String decompile(Function function) {
        DecompInterface decompiler = new DecompInterface();
        try {
            decompiler.openProgram(currentProgram);
            DecompileResults result = decompiler.decompileFunction(function, 30, monitor);
            if (result == null || !result.decompileCompleted() || result.getDecompiledFunction() == null) {
                String error = result == null ? "null result" : result.getErrorMessage();
                return "/* decompile failed: " + error + " */\n";
            }
            return result.getDecompiledFunction().getC();
        }
        finally {
            decompiler.dispose();
        }
    }

    private String formatBytes(byte[] bytes) {
        StringBuilder builder = new StringBuilder();
        for (byte value : bytes) {
            if (builder.length() > 0) {
                builder.append(' ');
            }
            builder.append(String.format("%02x", value & 0xff));
        }
        return builder.toString();
    }

    private static class Hit {
        final String address;
        final String functionName;
        final Function function;
        final String offset;
        final String bytes;
        final String instruction;

        Hit(String address, String functionName, Function function, String offset, String bytes, String instruction) {
            this.address = address;
            this.functionName = functionName;
            this.function = function;
            this.offset = offset;
            this.bytes = bytes;
            this.instruction = instruction;
        }
    }
}
