// Whole-program Ghidra probe for video-state accesses fed by sideband fields.

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSetView;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ProbeHp1020VideoStateSidebandAccessScan extends GhidraScript {
    private static final Target[] TARGET_OFFSETS = {
        new Target("+0xd0", 0xd0, "candidate video-state sideband-derived offset"),
        new Target("+0xd4", 0xd4, "candidate video-state sideband-derived offset"),
        new Target("+0xe8", 0xe8, "candidate video-state sideband-derived offset"),
        new Target("+0xec", 0xec, "candidate video-state sideband-derived offset")
    };
    private static final long[] KNOWN_FUNCTION_STARTS = {
        0x10013f34L,
        0x100140f8L,
        0x10014244L,
        0x10014910L
    };

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            println("usage: ProbeHp1020VideoStateSidebandAccessScan <output-dir>");
            return;
        }

        File outDir = new File(args[0]);
        outDir.mkdirs();
        File outFile = new File(outDir, "video-state-sideband-access-scan.md");

        createKnownFunctions();
        List<Hit> hits = scanInstructions();

        try (PrintWriter out = new PrintWriter(new FileWriter(outFile))) {
            out.println("# HP 1020 Video State Sideband Access Scan");
            out.println();
            out.println("This report is generated by headless Ghidra. It scans disassembled load/store instructions only and does not contact the printer.");
            out.println();
            out.println("## Import Context");
            out.println();
            out.println("- program: `" + currentProgram.getName() + "`");
            out.println("- language: `" + currentProgram.getLanguageID() + "`");
            out.println("- compiler spec: `" + currentProgram.getCompilerSpec().getCompilerSpecID() + "`");
            out.println("- target offsets: `+0xd0`, `+0xd4`, `+0xe8`, `+0xec`");
            out.println("- matching accesses: `" + hits.size() + "`");
            out.println();

            out.println("## Access Hits");
            out.println();
            out.println("| Address | Function | Access | Offset | Meaning | Bytes | Instruction |");
            out.println("|---|---|---|---:|---|---|---|");
            for (Hit hit : hits) {
                out.printf("| `%s` | `%s` | `%s` | `0x%x` | %s | `%s` | `%s` |%n",
                    hit.address,
                    hit.functionName,
                    hit.access,
                    hit.offset,
                    hit.meaning,
                    hit.bytes,
                    hit.instruction.replace("|", "\\|"));
            }

            out.println();
            out.println("## Decompiled Hit Functions");
            out.println();
            Map<Function, Boolean> seen = new LinkedHashMap<>();
            for (Hit hit : hits) {
                if (hit.function != null) {
                    seen.put(hit.function, Boolean.TRUE);
                }
            }
            for (Function function : seen.keySet()) {
                out.println("### `" + function.getEntryPoint() + " " + function.getName() + "`");
                out.println();
                out.println("```c");
                out.print(decompile(function));
                out.println("```");
                out.println();
            }
        }
        println("wrote " + outFile.getAbsolutePath());
    }

    private void createKnownFunctions() throws Exception {
        for (long raw : KNOWN_FUNCTION_STARTS) {
            Address address = toAddr(raw);
            disassemble(address);
            Function function = getFunctionAt(address);
            if (function == null) {
                function = createFunction(address, "hp1020_probe_fn_" + Long.toHexString(raw));
            }
            if (function != null && function.getName().startsWith("hp1020_probe_fn_")) {
                function.setName("hp1020_probe_fn_" + Long.toHexString(raw), SourceType.ANALYSIS);
            }
        }
    }

    private List<Hit> scanInstructions() throws Exception {
        List<Hit> hits = new ArrayList<>();
        AddressSetView executable = currentProgram.getMemory().getExecuteSet();
        InstructionIterator instructions = currentProgram.getListing().getInstructions(executable, true);
        while (instructions.hasNext()) {
            Instruction instruction = instructions.next();
            Access access = parseAccess(instruction.toString());
            if (access == null) {
                continue;
            }
            Target target = targetFor(access.offset);
            if (target == null) {
                continue;
            }
            Function function = getFunctionContaining(instruction.getAddress());
            hits.add(new Hit(
                instruction.getAddress().toString(),
                function == null ? "<none>" : function.getEntryPoint() + " " + function.getName(),
                function,
                access.kind,
                access.offset,
                target.meaning,
                formatBytes(instruction.getBytes()),
                instruction.toString()
            ));
        }
        return hits;
    }

    private Access parseAccess(String text) {
        String lower = text.toLowerCase();
        String kind;
        if (lower.startsWith("l8ui ") || lower.startsWith("l16ui ") ||
            lower.startsWith("l32i ") || lower.startsWith("l32i.n ")) {
            kind = "load";
        }
        else if (lower.startsWith("s8i ") || lower.startsWith("s16i ") ||
                 lower.startsWith("s32i ") || lower.startsWith("s32i.n ")) {
            kind = "store";
        }
        else {
            return null;
        }
        int comma = lower.lastIndexOf(',');
        if (comma < 0 || comma + 1 >= lower.length()) {
            return null;
        }
        String offsetText = lower.substring(comma + 1).trim();
        if (!offsetText.startsWith("0x")) {
            return null;
        }
        try {
            int offset = Integer.parseUnsignedInt(offsetText.substring(2), 16);
            return new Access(kind, offset);
        }
        catch (NumberFormatException ignored) {
            return null;
        }
    }

    private Target targetFor(int offset) {
        for (Target target : TARGET_OFFSETS) {
            if (target.offset == offset) {
                return target;
            }
        }
        return null;
    }

    private String decompile(Function function) {
        DecompInterface decompiler = new DecompInterface();
        try {
            decompiler.openProgram(currentProgram);
            DecompileResults result = decompiler.decompileFunction(function, 30, monitor);
            if (result == null || !result.decompileCompleted() || result.getDecompiledFunction() == null) {
                String error = result == null ? "null result" : result.getErrorMessage();
                return "/* decompile failed: " + error + " */\n";
            }
            return result.getDecompiledFunction().getC();
        }
        finally {
            decompiler.dispose();
        }
    }

    private String formatBytes(byte[] bytes) {
        StringBuilder builder = new StringBuilder();
        for (byte value : bytes) {
            if (builder.length() > 0) {
                builder.append(' ');
            }
            builder.append(String.format("%02x", value & 0xff));
        }
        return builder.toString();
    }

    private static class Target {
        final String name;
        final int offset;
        final String meaning;

        Target(String name, int offset, String meaning) {
            this.name = name;
            this.offset = offset;
            this.meaning = meaning;
        }
    }

    private static class Access {
        final String kind;
        final int offset;

        Access(String kind, int offset) {
            this.kind = kind;
            this.offset = offset;
        }
    }

    private static class Hit {
        final String address;
        final String functionName;
        final Function function;
        final String access;
        final int offset;
        final String meaning;
        final String bytes;
        final String instruction;

        Hit(String address, String functionName, Function function, String access, int offset,
            String meaning, String bytes, String instruction) {
            this.address = address;
            this.functionName = functionName;
            this.function = function;
            this.access = access;
            this.offset = offset;
            this.meaning = meaning;
            this.bytes = bytes;
            this.instruction = instruction;
        }
    }
}
