// Focused Ghidra probe for 0x100104c8 hp1020_work_populate_from_page_params_candidate.

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

public class ProbeHp1020WorkPopulate extends GhidraScript {
    private static final long ENTRY = 0x100104c8L;
    private static final long END_EXCLUSIVE = 0x10010520L;

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            println("usage: ProbeHp1020WorkPopulate <output-dir>");
            return;
        }

        File outDir = new File(args[0]);
        outDir.mkdirs();
        File outFile = new File(outDir, "work-populate-instruction-probe.md");

        Address entry = toAddr(ENTRY);
        disassemble(entry);
        Function function = getFunctionAt(entry);
        if (function == null) {
            function = createFunction(entry, "hp1020_work_populate_from_page_params_candidate");
        }
        if (function != null) {
            function.setName("hp1020_work_populate_from_page_params_candidate", SourceType.ANALYSIS);
        }

        try (PrintWriter out = new PrintWriter(new FileWriter(outFile))) {
            out.println("# HP 1020 Work Populate Instruction Probe");
            out.println();
            out.println("This report is generated by headless Ghidra. It does not contact the printer.");
            out.println();
            out.println("## Import Context");
            out.println();
            out.println("- program: `" + currentProgram.getName() + "`");
            out.println("- language: `" + currentProgram.getLanguageID() + "`");
            out.println("- compiler spec: `" + currentProgram.getCompilerSpec().getCompilerSpecID() + "`");
            out.println("- function: `0x100104c8 hp1020_work_populate_from_page_params_candidate`");
            out.println();

            out.println("## Instructions");
            out.println();
            out.println("| Address | Bytes | Instruction |");
            out.println("|---|---|---|");
            Address cursor = entry;
            int count = 0;
            while (cursor.getOffset() < END_EXCLUSIVE && count < 64) {
                Instruction instruction = getInstructionAt(cursor);
                if (instruction == null) {
                    boolean ok = disassemble(cursor);
                    instruction = getInstructionAt(cursor);
                    if (!ok || instruction == null) {
                        out.printf("| `%s` |  | `<no instruction>` |%n", cursor);
                        cursor = cursor.add(1);
                        count++;
                        continue;
                    }
                }
                out.printf("| `%s` | `%s` | `%s` |%n",
                    instruction.getAddress(),
                    formatBytes(instruction.getBytes()),
                    escape(instruction.toString()));
                cursor = instruction.getMaxAddress().add(1);
                count++;
                String mnemonic = instruction.getMnemonicString().toLowerCase();
                if (mnemonic.startsWith("ret")) {
                    break;
                }
            }

            out.println();
            out.println("## Decompiled C");
            out.println();
            out.println("```c");
            out.print(decompile(function));
            out.println("```");
        }
        println("wrote " + outFile.getAbsolutePath());
    }

    private String decompile(Function function) {
        if (function == null) {
            return "/* function creation failed */\n";
        }
        DecompInterface decompiler = new DecompInterface();
        try {
            decompiler.openProgram(currentProgram);
            DecompileResults result = decompiler.decompileFunction(function, 30, monitor);
            if (result == null || !result.decompileCompleted() || result.getDecompiledFunction() == null) {
                String error = result == null ? "null result" : result.getErrorMessage();
                return "/* decompile failed: " + error + " */\n";
            }
            return result.getDecompiledFunction().getC();
        }
        finally {
            decompiler.dispose();
        }
    }

    private String formatBytes(byte[] bytes) {
        StringBuilder builder = new StringBuilder();
        for (byte value : bytes) {
            if (builder.length() > 0) {
                builder.append(' ');
            }
            builder.append(String.format("%02x", value & 0xff));
        }
        return builder.toString();
    }

    private String escape(String value) {
        return value.replace("|", "\\|");
    }
}
